<script lang="ts">
	import type { PageProps } from './$types';
	let { data, form }: PageProps = $props();
</script>

<svelte:head><title>Stammdaten – Administration – AbiPro</title></svelte:head>
<main>
	<p><a href="/admin">Administration</a></p><h1>Stammdaten</h1>
	{#if form?.message}<p role="status">{form.message}</p>{/if}
	<section><h2>Lehrpläne</h2><form method="POST" action="?/saveCurriculum"><label>Code <input name="code" required /></label><label>Name <input name="name" required /></label><button>Hinzufügen</button></form>{#each data.curricula as item (item.id)}<form method="POST" action="?/saveCurriculum"><input type="hidden" name="id" value={item.id} /><label>Code <input name="code" value={item.code} required /></label><label>Name <input name="name" value={item.name} required /></label><button>Speichern</button><button formaction="?/deleteCurriculum">Löschen</button></form>{/each}</section>
	<section><h2>Epochen</h2><form method="POST" action="?/savePeriod"><label>Slug <input name="slug" required /></label><label>Name <input name="name" required /></label><label>Position <input name="position" type="number" min="0" value="0" required /></label><button>Hinzufügen</button></form>{#each data.periods as item (item.id)}<form method="POST" action="?/savePeriod"><input type="hidden" name="id" value={item.id} /><label>Slug <input name="slug" value={item.slug} required /></label><label>Name <input name="name" value={item.name} required /></label><label>Position <input name="position" type="number" min="0" value={item.position} required /></label><button>Speichern</button><button formaction="?/deletePeriod">Löschen</button></form>{/each}</section>
	<section><h2>Themen</h2><form method="POST" action="?/saveTopic"><label>Slug <input name="slug" required /></label><label>Name <input name="name" required /></label><label>Epoche <select name="periodId" required>{#each data.periods as period (period.id)}<option value={period.id}>{period.name}</option>{/each}</select></label><button>Hinzufügen</button></form>{#each data.topics as item (item.id)}<form method="POST" action="?/saveTopic"><input type="hidden" name="id" value={item.id} /><label>Slug <input name="slug" value={item.slug} required /></label><label>Name <input name="name" value={item.name} required /></label><label>Epoche <select name="periodId" value={item.periodId}>{#each data.periods as period (period.id)}<option value={period.id}>{period.name}</option>{/each}</select></label><button>Speichern</button><button formaction="?/deleteTopic">Löschen</button></form>{/each}</section>
	<section><h2>Prüfungstermine</h2><form method="POST" action="?/saveSession"><label>Jahr <input name="year" type="number" min="2000" max="2100" required /></label><label>Session <select name="session"><option value="spring">Frühjahr</option><option value="autumn">Herbst</option></select></label><label>Offizieller Code <input name="officialCode" /></label><button>Hinzufügen</button></form>{#each data.sessions as item (item.id)}<form method="POST" action="?/saveSession"><input type="hidden" name="id" value={item.id} /><label>Jahr <input name="year" type="number" value={item.year} required /></label><label>Session <select name="session" value={item.session}><option value="spring">Frühjahr</option><option value="autumn">Herbst</option></select></label><label>Offizieller Code <input name="officialCode" value={item.officialCode ?? ''} /></label><button>Speichern</button><button formaction="?/deleteSession">Löschen</button></form>{/each}</section>
</main>
