<script lang="ts">
	import type { PageProps } from './$types';
	let { data, form }: PageProps = $props();
	const years = $derived([...new Set(data.sessions.map((session) => session.year))]);
</script>

<svelte:head><title>Aufgabenverwaltung – AbiPro</title></svelte:head>
<main>
	<p><a href="/admin">Administration</a></p><h1>Aufgabenverwaltung</h1>
	{#if form?.message}<p role="status">{form.message}</p>{/if}
	<section><h2>Filtern</h2><form method="GET"><label>Suche <input name="q" type="search" value={data.filters.query ?? ''} /></label><label>Status <select name="status"><option value="">Alle</option><option value="draft" selected={data.filters.status === 'draft'}>Entwurf</option><option value="published" selected={data.filters.status === 'published'}>Veröffentlicht</option><option value="archived" selected={data.filters.status === 'archived'}>Archiviert</option></select></label><label>Lehrplan <select name="curriculumId"><option value="">Alle</option>{#each data.curricula as item (item.id)}<option value={item.id} selected={data.filters.curriculumId === item.id}>{item.name}</option>{/each}</select></label><label>Epoche <select name="periodId"><option value="">Alle</option>{#each data.periods as item (item.id)}<option value={item.id} selected={data.filters.periodId === item.id}>{item.name}</option>{/each}</select></label><label>Thema <select name="topicId"><option value="">Alle</option>{#each data.topics as item (item.id)}<option value={item.id} selected={data.filters.topicId === item.id}>{item.name}</option>{/each}</select></label><label>Jahr <select name="year"><option value="">Alle</option>{#each years as year (year)}<option value={year} selected={data.filters.year === year}>{year}</option>{/each}</select></label><button>Filtern</button><a href="/admin/aufgaben">Zurücksetzen</a></form></section>

	<section><h2>Neue Aufgabe</h2>{#if !data.periods.length || !data.sessions.length || !data.curricula.length}<p>Lege zuerst die benötigten <a href="/admin/stammdaten">Stammdaten</a> an.</p>{:else}<form method="POST" action="?/create"><label>Slug <input name="slug" value={form?.values?.slug?.toString() ?? ''} required /></label><label>Titel <input name="title" value={form?.values?.title?.toString() ?? ''} required /></label><label>Anweisung <textarea name="instructions">{form?.values?.instructions?.toString() ?? ''}</textarea></label><label>Lehrplan <select name="curriculumId">{#each data.curricula as item (item.id)}<option value={item.id}>{item.name}</option>{/each}</select></label><label>Epoche <select name="periodId">{#each data.periods as item (item.id)}<option value={item.id}>{item.name}</option>{/each}</select></label><label>Prüfungstermin <select name="examSessionId">{#each data.sessions as item (item.id)}<option value={item.id}>{item.year} – {item.session === 'spring' ? 'Frühjahr' : 'Herbst'}</option>{/each}</select></label><label>Offizielle Position im Kurzantwort-Teil <select name="examPosition"><option value="">Nicht für Prüfungen</option>{#each Array.from({ length: 12 }, (_, index) => index + 1) as position (position)}<option value={position}>{position}</option>{/each}</select></label><label>Maximalpunktzahl <input name="maxPoints" type="number" min="0.25" step="0.25" required /></label><button>Entwurf erstellen</button></form>{/if}</section>

	<section><h2>Aufgaben ({data.taskVersions.length})</h2>{#if data.taskVersions.length}<table><thead><tr><th>Titel</th><th>Jahr</th><th>Version</th><th>Status</th><th>Aktionen</th></tr></thead><tbody>{#each data.taskVersions as item (item.taskId)}<tr><td><a href={`/admin/aufgaben/${item.versionId}`}>{item.title}</a><br /><code>{item.slug}</code></td><td>{item.year}</td><td>{item.version}</td><td>{item.taskStatus === 'archived' ? 'archived' : item.versionStatus}</td><td><form method="POST" action={item.taskStatus === 'archived' ? '?/restore' : '?/archive'}><input type="hidden" name="taskId" value={item.taskId} /><button>{item.taskStatus === 'archived' ? 'Wiederherstellen' : 'Archivieren'}</button></form></td></tr>{/each}</tbody></table>{:else}<p>Keine Aufgaben entsprechen den Filtern.</p>{/if}</section>
</main>
