<script lang="ts">
	import type { EditableQuestion, EditorOption, QuestionKind } from '$lib/types/admin';

	interface Props { question: EditableQuestion; index: number; total: number; onchange: () => void; onmove: (direction: -1 | 1) => void; onduplicate: () => void; onremove: () => void }
	let { question = $bindable(), index, total, onchange, onmove, onduplicate, onremove }: Props = $props();

	function nextId(items: EditorOption[]) { let index = items.length + 1; while (items.some((item) => item.id === `o${index}`)) index += 1; return `o${index}`; }
	function addOption(items: EditorOption[]) { items.push({ id: nextId(items), label: '' }); onchange(); }
	function removeOption(items: EditorOption[], optionIndex: number) { const [removed] = items.splice(optionIndex, 1); question.correctOptionIds = question.correctOptionIds.filter((id) => id !== removed.id); question.correctOrder = question.correctOrder.filter((id) => id !== removed.id); question.pairs = question.pairs.filter((pair) => pair.leftId !== removed.id && pair.rightId !== removed.id); onchange(); }
	function changeKind(kind: QuestionKind) { question.kind = kind; if ((kind === 'choice' || kind === 'multiple_choice') && question.options.length < 2) question.options = [{ id: 'a', label: '' }, { id: 'b', label: '' }]; if (kind === 'choice' && !question.correctOptionIds.length) question.correctOptionIds = [question.options[0].id]; if (kind === 'matching' && (!question.left.length || !question.right.length)) { question.left = [{ id: 'a', label: '' }]; question.right = [{ id: '1', label: '' }]; question.pairs = [{ leftId: 'a', rightId: '1' }]; } if (kind === 'ordering' && question.items.length < 2) { question.items = [{ id: 'a', label: '' }, { id: 'b', label: '' }]; question.correctOrder = ['a', 'b']; } if (kind === 'short_text' && !question.criteria.length) question.criteria = ['']; onchange(); }
	function toggleCorrect(id: string, checked: boolean) { question.correctOptionIds = checked ? [...new Set([...question.correctOptionIds, id])] : question.correctOptionIds.filter((value) => value !== id); }
	function moveOrder(index: number, direction: -1 | 1) { const target = index + direction; if (target < 0 || target >= question.correctOrder.length) return; [question.correctOrder[index], question.correctOrder[target]] = [question.correctOrder[target], question.correctOrder[index]]; onchange(); }
</script>

<article>
	<h3>Frage {index + 1}</h3>
	<p><button type="button" onclick={() => onmove(-1)} disabled={index === 0}>Nach oben</button> <button type="button" onclick={() => onmove(1)} disabled={index === total - 1}>Nach unten</button> <button type="button" onclick={onduplicate}>Duplizieren</button> <button type="button" onclick={onremove}>Entfernen</button></p>
	<p><label>Typ <select value={question.kind} onchange={(event) => changeKind(event.currentTarget.value as QuestionKind)}><option value="choice">Einfachauswahl</option><option value="multiple_choice">Mehrfachauswahl</option><option value="matching">Zuordnung</option><option value="ordering">Reihenfolge</option><option value="short_text">Freitext</option></select></label></p>
	<p><label>Fragetext <textarea bind:value={question.prompt} rows="3" required></textarea></label></p>
	<p><label>Punkte <input bind:value={question.maxPoints} type="number" min="0.25" step="0.25" required /></label></p>

	{#if question.kind === 'choice' || question.kind === 'multiple_choice'}
		<h4>Antwortmöglichkeiten</h4>
		{#each question.options as option, optionIndex (`${question.clientId}-option-${optionIndex}`)}<fieldset><legend>Option {optionIndex + 1}</legend><label>ID <input bind:value={option.id} required /></label><label>Text <input bind:value={option.label} required /></label>{#if question.kind === 'choice'}<label><input type="radio" name={`correct-${question.clientId}`} value={option.id} checked={question.correctOptionIds[0] === option.id} onchange={() => question.correctOptionIds = [option.id]} /> Richtige Antwort</label>{:else}<label><input type="checkbox" checked={question.correctOptionIds.includes(option.id)} onchange={(event) => toggleCorrect(option.id, event.currentTarget.checked)} /> Richtige Antwort</label>{/if}<button type="button" onclick={() => removeOption(question.options, optionIndex)} disabled={question.options.length <= 2}>Option entfernen</button></fieldset>{/each}
		<p><button type="button" onclick={() => addOption(question.options)}>Option hinzufügen</button></p>
		{#if question.kind === 'multiple_choice'}<p><label>Mindestauswahl (optional) <input type="number" min="0" bind:value={question.minimumSelections} /></label></p><p><label>Maximalauswahl (optional) <input type="number" min="1" bind:value={question.maximumSelections} /></label></p><label><input type="checkbox" bind:checked={question.allOrNothing} /> Nur vollständig richtige Auswahl bewerten</label>{/if}
	{:else if question.kind === 'matching'}
		<h4>Linke Seite</h4>{#each question.left as option, optionIndex (`${question.clientId}-left-${optionIndex}`)}<fieldset><label>ID <input bind:value={option.id} required /></label><label>Text <input bind:value={option.label} required /></label><button type="button" onclick={() => removeOption(question.left, optionIndex)} disabled={question.left.length <= 1}>Entfernen</button></fieldset>{/each}<p><button type="button" onclick={() => addOption(question.left)}>Eintrag hinzufügen</button></p>
		<h4>Rechte Seite</h4>{#each question.right as option, optionIndex (`${question.clientId}-right-${optionIndex}`)}<fieldset><label>ID <input bind:value={option.id} required /></label><label>Text <input bind:value={option.label} required /></label><button type="button" onclick={() => removeOption(question.right, optionIndex)} disabled={question.right.length <= 1}>Entfernen</button></fieldset>{/each}<p><button type="button" onclick={() => addOption(question.right)}>Eintrag hinzufügen</button></p>
		<h4>Korrekte Paare</h4>{#each question.pairs as pair, pairIndex (`${question.clientId}-pair-${pairIndex}`)}<fieldset><label>Links <select bind:value={pair.leftId}>{#each question.left as option (option.id)}<option value={option.id}>{option.label || option.id}</option>{/each}</select></label><label>Rechts <select bind:value={pair.rightId}>{#each question.right as option (option.id)}<option value={option.id}>{option.label || option.id}</option>{/each}</select></label><button type="button" onclick={() => { question.pairs.splice(pairIndex, 1); onchange(); }} disabled={question.pairs.length <= 1}>Paar entfernen</button></fieldset>{/each}<p><button type="button" onclick={() => { question.pairs.push({ leftId: question.left[0]?.id ?? '', rightId: question.right[0]?.id ?? '' }); onchange(); }}>Paar hinzufügen</button></p>
	{:else if question.kind === 'ordering'}
		<h4>Elemente</h4>{#each question.items as option, optionIndex (`${question.clientId}-item-${optionIndex}`)}<fieldset><label>ID <input bind:value={option.id} required /></label><label>Text <input bind:value={option.label} required /></label><button type="button" onclick={() => removeOption(question.items, optionIndex)} disabled={question.items.length <= 2}>Entfernen</button></fieldset>{/each}<p><button type="button" onclick={() => { const item = { id: nextId(question.items), label: '' }; question.items.push(item); question.correctOrder.push(item.id); onchange(); }}>Element hinzufügen</button></p>
		<h4>Korrekte Reihenfolge</h4><ol>{#each question.correctOrder as itemId, orderIndex (`${question.clientId}-order-${itemId}`)}<li>{question.items.find((item) => item.id === itemId)?.label || itemId} <button type="button" onclick={() => moveOrder(orderIndex, -1)} disabled={orderIndex === 0}>Hoch</button> <button type="button" onclick={() => moveOrder(orderIndex, 1)} disabled={orderIndex === question.correctOrder.length - 1}>Runter</button></li>{/each}</ol>
	{:else}
		<label><input type="checkbox" bind:checked={question.multiline} /> Mehrzeilige Antwort</label><p><label>Maximale Zeichen (optional) <input bind:value={question.maximumLength} type="number" min="1" /></label></p>
		<h4>Akzeptierte Antworten</h4>{#each question.acceptedAnswers as _answer, answerIndex (`${question.clientId}-answer-${answerIndex}`)}<p><label>Antwort <input bind:value={question.acceptedAnswers[answerIndex]} /></label> <button type="button" onclick={() => { question.acceptedAnswers.splice(answerIndex, 1); onchange(); }}>Entfernen</button></p>{/each}<p><button type="button" onclick={() => { question.acceptedAnswers.push(''); onchange(); }}>Antwort hinzufügen</button></p>
		<h4>Bewertungskriterien</h4>{#each question.criteria as _criterion, criterionIndex (`${question.clientId}-criterion-${criterionIndex}`)}<p><label>Kriterium <input bind:value={question.criteria[criterionIndex]} required /></label> <button type="button" onclick={() => { question.criteria.splice(criterionIndex, 1); onchange(); }} disabled={question.criteria.length <= 1}>Entfernen</button></p>{/each}<p><button type="button" onclick={() => { question.criteria.push(''); onchange(); }}>Kriterium hinzufügen</button></p><label><input type="checkbox" bind:checked={question.normalizeWhitespace} /> Mehrfache Leerzeichen beim exakten Vergleich zusammenfassen</label><label><input type="checkbox" bind:checked={question.aiEligible} /> Für KI-Bewertung geeignet</label>
	{/if}
</article>
